In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
b=np.array([2,4,6,8])
print(a,b)
print(np.inner(a,b))

[1 2 3 4] [2 4 6 8]
60


In [36]:
d=np.matrix([[1,2,3],[2,2,2]])
c=np.matrix([[2,4],[6,5],[4,3]])
print(type(c))
print(np.dot(c,d))

<class 'numpy.matrix'>
[[10 12 14]
 [16 22 28]
 [10 14 18]]


In [37]:
print(c)
print(" ")
print(np.transpose(c))

[[2 4]
 [6 5]
 [4 3]]
 
[[2 6 4]
 [4 5 3]]


In [38]:
c.transpose()

matrix([[2, 6, 4],
        [4, 5, 3]])

In [44]:
c.T

array([[2, 3],
       [2, 4]])

In [43]:
x=np.arange(1, 10)
x.shape=(3,3)
print(x)
rank=np.linalg.matrix_rank(x)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
c=np.array([[2,2],[3,4]])
det=np.linalg.det(c)
print(det)
print(np.round(det))

1.9999999999999998
2.0


In [46]:
a=np.array([[2,2,1],[1,3,1],[1,2,2]])
print(a)
det=np.linalg.det(a)
print(det)
print(np.round(det))
inv=np.linalg.inv(a)

[[2 2 1]
 [1 3 1]
 [1 2 2]]
4.999999999999999
5.0


In [48]:
a=np.array([[2,2,1],[1,3,1],[1,2,2]])
print(a)
w,v=np.linalg.eig(a)
print(w,v)

[[2 2 1]
 [1 3 1]
 [1 2 2]]
[5. 1. 1.] [[ 0.57735027  0.90453403  0.36601928]
 [ 0.57735027 -0.30151134 -0.55609927]
 [ 0.57735027 -0.30151134  0.74617926]]


In [49]:
a=np.array([[2,2,1],[1,3,1],[1,2,2]])
print(a)
w=np.linalg.eig(a)
print(w)

[[2 2 1]
 [1 3 1]
 [1 2 2]]
(array([5., 1., 1.]), array([[ 0.57735027,  0.90453403,  0.36601928],
       [ 0.57735027, -0.30151134, -0.55609927],
       [ 0.57735027, -0.30151134,  0.74617926]]))


# operations

In [50]:
a1=np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [51]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [52]:
print(a2[0,2])

3


In [54]:
a3=np.array([1,2,3,4,5])
print(a3)
a4=a3+2
print(a4)

[1 2 3 4 5]
[3 4 5 6 7]


In [55]:
a5=a3*2
print(a5)

[ 2  4  6  8 10]


In [58]:
print(np.sum(a3))
print(np.mean(a3))
print(np.max(a3))
print(np.min(a3))
print(np.std(a3))

15
3.0
5
1
1.4142135623730951
