In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

In [16]:
a=np.array([[1,2,3],[4,5,6],[59,46,34],[8,2,3]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [59 46 34]
 [ 8  2  3]]


In [17]:
a.ndim

2

In [8]:
b=np.array([[[1,2,3],[4,5,6],[59,46,34],[8,2,3]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [59 46 34]
  [ 8  2  3]]]


In [15]:
b.ndim

3

In [10]:
c=np.array([[[[1,2,3],[4,5,6],[59,46,34],[8,2,3]]]])
print(c)

[[[[ 1  2  3]
   [ 4  5  6]
   [59 46 34]
   [ 8  2  3]]]]


In [14]:
print(c.ndim)

4


In [20]:
d=np.array([1,2,3])
print(d)
print(d.ndim)

[1 2 3]
1


In [21]:
x=np.array([1,2,3,4,5])
c=0
for i in range(len(x)):
    c=c+x[i]
print(c)

6


In [26]:
x=np.array([[1,2,3,4,5],[9,8,7,6,5],[1,2,3,4,5],[5,4,3,2,1]])
c=0
for i in range(len(x)):
    c=c+x[i][1]
print(c)

16


In [27]:
x[2,0]

1

In [28]:
x=np.array(
    [[[1,2,3,4,5],[9,8,7,6,5],[1,2,3,4,5],[5,4,3,2,1]][1,2,3,4,5],[9,8,7,6,5],[1,2,3,4,5],[5,4,3,2,1]]
)
c=0
for i in range(len(x)):
    c=c+x[i][1]
print(c)

[9 8 7 6 5]


In [30]:
print(x[][][])

SyntaxError: invalid syntax (<ipython-input-30-554f97449f11>, line 1)

In [32]:
a = np.array(
    [
    [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ],  
    [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ],  
    ]
)

In [38]:
c=0
d=0
for i in range(4):
    c=c+a[0][0][i]
    d=d+a[1][0][i]
print(c+d)

20


In [40]:
a = np.array(
    [1,2,3,4,5,6,7,8,9,10,11,12]
)
print(a[0:6])

[1 2 3 4 5 6]


In [42]:
print(a[3:10])

[ 4  5  6  7  8  9 10]


In [43]:
print(a[-7:10])

[ 6  7  8  9 10]


In [48]:
print(a[0:12:2])

[ 1  3  5  7  9 11]


In [52]:
arr=np.array([[[1,2,3,2,3,4,5],[2,3,4,5,6],[1,2,3]]])
print(arr)
  

[[list([1, 2, 3, 2, 3, 4, 5]) list([2, 3, 4, 5, 6]) list([1, 2, 3])]]


<ipython-input-52-56768b70606f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[[1,2,3,2,3,4,5],[2,3,4,5,6],[1,2,3]]])


In [55]:
p=np.array([1,2,3,4,5,6,7,8,9,10])
print(p.ndim)
print(p.reshape(2,5))

1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
p=np.array([[1,2,3]])
q=np.array([[4,5,6]])
print(np.concatenate((p,q)))

[[1 2 3]
 [4 5 6]]


In [71]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=np.array_split(a,4)
print(x,"\n")
print(a.reshape(2,6))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
