In [2]:
import matplotlib.pyplot as pt
import numpy as np

In [5]:
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [9]:
p=[[1,2,3],[4,5,6],[8,9,10]]
print(p,"\n\n")
print(np.array(p))

[[1, 2, 3], [4, 5, 6], [8, 9, 10]] 


[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [10]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [13]:
print(np.zeros([4,3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
print(np.ones([2,2]))

[[1. 1.]
 [1. 1.]]


In [18]:
#(start,end,eqaul division)
np.linspace(1,5,70)

array([1.        , 1.05797101, 1.11594203, 1.17391304, 1.23188406,
       1.28985507, 1.34782609, 1.4057971 , 1.46376812, 1.52173913,
       1.57971014, 1.63768116, 1.69565217, 1.75362319, 1.8115942 ,
       1.86956522, 1.92753623, 1.98550725, 2.04347826, 2.10144928,
       2.15942029, 2.2173913 , 2.27536232, 2.33333333, 2.39130435,
       2.44927536, 2.50724638, 2.56521739, 2.62318841, 2.68115942,
       2.73913043, 2.79710145, 2.85507246, 2.91304348, 2.97101449,
       3.02898551, 3.08695652, 3.14492754, 3.20289855, 3.26086957,
       3.31884058, 3.37681159, 3.43478261, 3.49275362, 3.55072464,
       3.60869565, 3.66666667, 3.72463768, 3.7826087 , 3.84057971,
       3.89855072, 3.95652174, 4.01449275, 4.07246377, 4.13043478,
       4.1884058 , 4.24637681, 4.30434783, 4.36231884, 4.42028986,
       4.47826087, 4.53623188, 4.5942029 , 4.65217391, 4.71014493,
       4.76811594, 4.82608696, 4.88405797, 4.94202899, 5.        ])

In [19]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [27]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [37]:
np.random.randint(1,10,7)

array([3, 9, 5, 1, 8, 7, 3])

In [43]:
arr=np.arange(10)
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [101]:
z=np.random.randint(0,20,4)
print(z)
print(z.max())
print(min(z))

[7 8 8 4]
8
4


In [54]:
z.argmax()

0

In [70]:
z.reshape(4,4)
z.shape

ValueError: cannot reshape array of size 4 into shape (4,4)

In [75]:
np.arange("a,"z")

SyntaxError: invalid syntax (<ipython-input-75-168040a11126>, line 1)

In [77]:
l=np.arange(1,10,1)
print(l)

[1 2 3 4 5 6 7 8 9]


In [81]:
l[1:5]=100
print(l)

[  1 100 100 100 100   6   7   8   9]


In [87]:
p=[[1,2,3],[4,5,6],[8,9,10]]


In [88]:
a=np.arange(1,11)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [90]:
a+a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
l=[1,2,3,5,4]
i=[2,3,4,5,6]
l+i

[1, 2, 3, 5, 4, 2, 3, 4, 5, 6]

In [92]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

task

In [94]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [97]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [99]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [109]:
w=np.arange(0,9)
w.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [127]:
np.random.rand(1)

array([0.45124977])

In [134]:
np.arange(0.1,1.01,0.01)

array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
       0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53,
       0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64,
       0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75,
       0.76, 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86,
       0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97,
       0.98, 0.99, 1.  ])

In [135]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [137]:
x=np.arange(1,26).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [148]:
x[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [150]:
x[3,4]

20

In [170]:
x[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [171]:
x[4]

array([21, 22, 23, 24, 25])

In [172]:
x[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [174]:
np.sum(x)

325

In [175]:
np.std(x)

7.211102550927978

In [182]:
np.sum(x,axis=0)

array([55, 60, 65, 70, 75])